
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Expander expander2;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.ComboBox _environments;
	
	private global::Gtk.SpinButton _generationsToRun;
	
	private global::Gtk.SpinButton _genomeLength;
	
	private global::Gtk.SpinButton _lifetimeIterations;
	
	private global::Gtk.SpinButton _population;
	
	private global::Gtk.Button _reset;
	
	private global::Gtk.Label _resetWarning;
	
	private global::Gtk.HSeparator hseparator2;
	
	private global::Gtk.HSeparator hseparator4;
	
	private global::Gtk.HSeparator hseparator5;
	
	private global::Gtk.HSeparator hseparator6;
	
	private global::Gtk.HSeparator hseparator7;
	
	private global::Gtk.HSeparator hseparator8;
	
	private global::Gtk.HSeparator hseparator9;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Label GtkLabel1;
	
	private global::Gtk.HSeparator hseparator3;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label _generationLabel;
	
	private global::Gtk.Notebook notebook2;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Label _dCost1;
	
	private global::Gtk.Label _dCost2;
	
	private global::Gtk.Label _dining1;
	
	private global::Gtk.Label _dining2;
	
	private global::Gtk.Label _eCost1;
	
	private global::Gtk.Label _eCost2;
	
	private global::Gtk.Label _energy1;
	
	private global::Gtk.Label _energy2;
	
	private global::Gtk.Label _enzC1;
	
	private global::Gtk.Label _enzC2;
	
	private global::Gtk.Label _ex1;
	
	private global::Gtk.Label _ex2;
	
	private global::Gtk.Label _fEnz1;
	
	private global::Gtk.Label _fEnz2;
	
	private global::Gtk.Label _fitness1;
	
	private global::Gtk.Label _fitness2;
	
	private global::Gtk.Button _inject1;
	
	private global::Gtk.Button _inject2;
	
	private global::Gtk.Label _max1;
	
	private global::Gtk.Label _max2;
	
	private global::Gtk.Button _save1;
	
	private global::Gtk.Button _save2;
	
	private global::Gtk.Label _sEnz1;
	
	private global::Gtk.Label _sEnz2;
	
	private global::Gtk.Label _state1;
	
	private global::Gtk.Label _state2;
	
	private global::Gtk.Label label;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.Label label14;
	
	private global::Gtk.Label label15;
	
	private global::Gtk.Label label16;
	
	private global::Gtk.Label label17;
	
	private global::Gtk.Label label18;
	
	private global::Gtk.Label label25;
	
	private global::Gtk.Label label26;
	
	private global::Gtk.Label label28;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Button _action;
	
	private global::Gtk.Alignment alignment3;
	
	private global::Gtk.Button button5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Harness");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		this.vbox2.BorderWidth = ((uint)(3));
		// Container child vbox2.Gtk.Box+BoxChild
		this.expander2 = new global::Gtk.Expander (null);
		this.expander2.CanFocus = true;
		this.expander2.Name = "expander2";
		this.expander2.Expanded = true;
		// Container child expander2.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(7)), false);
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this._environments = global::Gtk.ComboBox.NewText ();
		this._environments.Name = "_environments";
		this.table1.Add (this._environments);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this._environments]));
		w2.LeftAttach = ((uint)(5));
		w2.RightAttach = ((uint)(6));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._generationsToRun = new global::Gtk.SpinButton (0, 10000000000, 1);
		this._generationsToRun.CanFocus = true;
		this._generationsToRun.Name = "_generationsToRun";
		this._generationsToRun.Adjustment.PageIncrement = 10;
		this._generationsToRun.ClimbRate = 1;
		this._generationsToRun.Numeric = true;
		this._generationsToRun.Value = 10;
		this.table1.Add (this._generationsToRun);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this._generationsToRun]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._genomeLength = new global::Gtk.SpinButton (0, 10000, 1);
		this._genomeLength.CanFocus = true;
		this._genomeLength.Name = "_genomeLength";
		this._genomeLength.Adjustment.PageIncrement = 10;
		this._genomeLength.ClimbRate = 1;
		this._genomeLength.Numeric = true;
		this._genomeLength.Value = 32;
		this.table1.Add (this._genomeLength);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this._genomeLength]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(3));
		w4.RightAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._lifetimeIterations = new global::Gtk.SpinButton (0, 10000000000, 1);
		this._lifetimeIterations.CanFocus = true;
		this._lifetimeIterations.Name = "_lifetimeIterations";
		this._lifetimeIterations.Adjustment.PageIncrement = 10;
		this._lifetimeIterations.ClimbRate = 1;
		this._lifetimeIterations.Numeric = true;
		this._lifetimeIterations.Value = 1000;
		this.table1.Add (this._lifetimeIterations);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this._lifetimeIterations]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._population = new global::Gtk.SpinButton (0, 10000000000, 1);
		this._population.CanFocus = true;
		this._population.Name = "_population";
		this._population.Adjustment.PageIncrement = 10;
		this._population.ClimbRate = 1;
		this._population.Numeric = true;
		this._population.Value = 10000;
		this.table1.Add (this._population);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this._population]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._reset = new global::Gtk.Button ();
		this._reset.CanFocus = true;
		this._reset.Name = "_reset";
		this._reset.UseUnderline = true;
		this._reset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.table1.Add (this._reset);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this._reset]));
		w7.LeftAttach = ((uint)(6));
		w7.RightAttach = ((uint)(7));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._resetWarning = new global::Gtk.Label ();
		this._resetWarning.Name = "_resetWarning";
		this._resetWarning.LabelProp = global::Mono.Unix.Catalog.GetString ("Click Reset To Apply Changes");
		this.table1.Add (this._resetWarning);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this._resetWarning]));
		w8.TopAttach = ((uint)(3));
		w8.BottomAttach = ((uint)(4));
		w8.LeftAttach = ((uint)(4));
		w8.RightAttach = ((uint)(5));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator2 = new global::Gtk.HSeparator ();
		this.hseparator2.Name = "hseparator2";
		this.table1.Add (this.hseparator2);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator2]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.table1.Add (this.hseparator4);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator4]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator5 = new global::Gtk.HSeparator ();
		this.hseparator5.Name = "hseparator5";
		this.table1.Add (this.hseparator5);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator5]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator6 = new global::Gtk.HSeparator ();
		this.hseparator6.Name = "hseparator6";
		this.table1.Add (this.hseparator6);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator6]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.LeftAttach = ((uint)(3));
		w12.RightAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator7 = new global::Gtk.HSeparator ();
		this.hseparator7.Name = "hseparator7";
		this.table1.Add (this.hseparator7);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator7]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(4));
		w13.RightAttach = ((uint)(5));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator8 = new global::Gtk.HSeparator ();
		this.hseparator8.Name = "hseparator8";
		this.table1.Add (this.hseparator8);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator8]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.LeftAttach = ((uint)(5));
		w14.RightAttach = ((uint)(6));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hseparator9 = new global::Gtk.HSeparator ();
		this.hseparator9.Name = "hseparator9";
		this.table1.Add (this.hseparator9);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator9]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.LeftAttach = ((uint)(6));
		w15.RightAttach = ((uint)(7));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.Xalign = 1F;
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Environment");
		this.table1.Add (this.label10);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
		w16.LeftAttach = ((uint)(4));
		w16.RightAttach = ((uint)(5));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.Ypad = 3;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Lifetime Iterations");
		this.label11.Justify = ((global::Gtk.Justification)(3));
		this.table1.Add (this.label11);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.label11]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Ypad = 3;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Pause After");
		this.label6.Justify = ((global::Gtk.Justification)(3));
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Ypad = 3;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Population Size");
		this.table1.Add (this.label7);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
		w19.TopAttach = ((uint)(3));
		w19.BottomAttach = ((uint)(4));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.Ypad = 3;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Genome Size");
		this.table1.Add (this.label8);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
		w20.TopAttach = ((uint)(3));
		w20.BottomAttach = ((uint)(4));
		w20.LeftAttach = ((uint)(2));
		w20.RightAttach = ((uint)(3));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Iterations");
		this.table1.Add (this.label9);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
		w21.LeftAttach = ((uint)(2));
		w21.RightAttach = ((uint)(3));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add (this.table1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table1]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.expander2.Add (this.vbox4);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		this.GtkLabel1.UseUnderline = true;
		this.expander2.LabelWidget = this.GtkLabel1;
		this.vbox2.Add (this.expander2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.expander2]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox2.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Generation");
		this.hbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._generationLabel = new global::Gtk.Label ();
		this._generationLabel.Name = "_generationLabel";
		this._generationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.hbox1.Add (this._generationLabel);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._generationLabel]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(14)), true);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		this.table2.BorderWidth = ((uint)(2));
		// Container child table2.Gtk.Table+TableChild
		this._dCost1 = new global::Gtk.Label ();
		this._dCost1.Name = "_dCost1";
		this._dCost1.Xalign = 0F;
		this._dCost1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._dCost1);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2 [this._dCost1]));
		w29.TopAttach = ((uint)(1));
		w29.BottomAttach = ((uint)(2));
		w29.LeftAttach = ((uint)(6));
		w29.RightAttach = ((uint)(7));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._dCost2 = new global::Gtk.Label ();
		this._dCost2.Name = "_dCost2";
		this._dCost2.Xalign = 0F;
		this._dCost2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._dCost2);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2 [this._dCost2]));
		w30.TopAttach = ((uint)(2));
		w30.BottomAttach = ((uint)(3));
		w30.LeftAttach = ((uint)(6));
		w30.RightAttach = ((uint)(7));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._dining1 = new global::Gtk.Label ();
		this._dining1.Name = "_dining1";
		this._dining1.Xalign = 0F;
		this._dining1.LabelProp = global::Mono.Unix.Catalog.GetString ("Energy");
		this.table2.Add (this._dining1);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2 [this._dining1]));
		w31.TopAttach = ((uint)(1));
		w31.BottomAttach = ((uint)(2));
		w31.LeftAttach = ((uint)(3));
		w31.RightAttach = ((uint)(4));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._dining2 = new global::Gtk.Label ();
		this._dining2.Name = "_dining2";
		this._dining2.Xalign = 0F;
		this._dining2.LabelProp = global::Mono.Unix.Catalog.GetString ("Energy");
		this.table2.Add (this._dining2);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table2 [this._dining2]));
		w32.TopAttach = ((uint)(2));
		w32.BottomAttach = ((uint)(3));
		w32.LeftAttach = ((uint)(3));
		w32.RightAttach = ((uint)(4));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._eCost1 = new global::Gtk.Label ();
		this._eCost1.Name = "_eCost1";
		this._eCost1.Xalign = 0F;
		this._eCost1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._eCost1);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2 [this._eCost1]));
		w33.TopAttach = ((uint)(1));
		w33.BottomAttach = ((uint)(2));
		w33.LeftAttach = ((uint)(7));
		w33.RightAttach = ((uint)(8));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._eCost2 = new global::Gtk.Label ();
		this._eCost2.Name = "_eCost2";
		this._eCost2.Xalign = 0F;
		this._eCost2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._eCost2);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2 [this._eCost2]));
		w34.TopAttach = ((uint)(2));
		w34.BottomAttach = ((uint)(3));
		w34.LeftAttach = ((uint)(7));
		w34.RightAttach = ((uint)(8));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._energy1 = new global::Gtk.Label ();
		this._energy1.Name = "_energy1";
		this._energy1.Xalign = 0F;
		this._energy1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._energy1);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table2 [this._energy1]));
		w35.TopAttach = ((uint)(1));
		w35.BottomAttach = ((uint)(2));
		w35.LeftAttach = ((uint)(4));
		w35.RightAttach = ((uint)(5));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._energy2 = new global::Gtk.Label ();
		this._energy2.Name = "_energy2";
		this._energy2.Xalign = 0F;
		this._energy2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._energy2);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2 [this._energy2]));
		w36.TopAttach = ((uint)(2));
		w36.BottomAttach = ((uint)(3));
		w36.LeftAttach = ((uint)(4));
		w36.RightAttach = ((uint)(5));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._enzC1 = new global::Gtk.Label ();
		this._enzC1.Name = "_enzC1";
		this._enzC1.Xalign = 0F;
		this._enzC1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._enzC1);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table2 [this._enzC1]));
		w37.TopAttach = ((uint)(1));
		w37.BottomAttach = ((uint)(2));
		w37.LeftAttach = ((uint)(9));
		w37.RightAttach = ((uint)(10));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._enzC2 = new global::Gtk.Label ();
		this._enzC2.Name = "_enzC2";
		this._enzC2.Xalign = 0F;
		this._enzC2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._enzC2);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table2 [this._enzC2]));
		w38.TopAttach = ((uint)(2));
		w38.BottomAttach = ((uint)(3));
		w38.LeftAttach = ((uint)(9));
		w38.RightAttach = ((uint)(10));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._ex1 = new global::Gtk.Label ();
		this._ex1.Name = "_ex1";
		this._ex1.Xalign = 0F;
		this._ex1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this._ex1.Wrap = true;
		this.table2.Add (this._ex1);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table2 [this._ex1]));
		w39.TopAttach = ((uint)(1));
		w39.BottomAttach = ((uint)(2));
		w39.LeftAttach = ((uint)(8));
		w39.RightAttach = ((uint)(9));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._ex2 = new global::Gtk.Label ();
		this._ex2.Name = "_ex2";
		this._ex2.Xalign = 0F;
		this._ex2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._ex2);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table2 [this._ex2]));
		w40.TopAttach = ((uint)(2));
		w40.BottomAttach = ((uint)(3));
		w40.LeftAttach = ((uint)(8));
		w40.RightAttach = ((uint)(9));
		w40.XOptions = ((global::Gtk.AttachOptions)(4));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._fEnz1 = new global::Gtk.Label ();
		this._fEnz1.Name = "_fEnz1";
		this._fEnz1.Xalign = 0F;
		this._fEnz1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._fEnz1);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table2 [this._fEnz1]));
		w41.TopAttach = ((uint)(1));
		w41.BottomAttach = ((uint)(2));
		w41.LeftAttach = ((uint)(10));
		w41.RightAttach = ((uint)(11));
		w41.XOptions = ((global::Gtk.AttachOptions)(4));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._fEnz2 = new global::Gtk.Label ();
		this._fEnz2.Name = "_fEnz2";
		this._fEnz2.Xalign = 0F;
		this._fEnz2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._fEnz2);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table2 [this._fEnz2]));
		w42.TopAttach = ((uint)(2));
		w42.BottomAttach = ((uint)(3));
		w42.LeftAttach = ((uint)(10));
		w42.RightAttach = ((uint)(11));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._fitness1 = new global::Gtk.Label ();
		this._fitness1.Name = "_fitness1";
		this._fitness1.Xalign = 0F;
		this._fitness1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._fitness1);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table2 [this._fitness1]));
		w43.TopAttach = ((uint)(1));
		w43.BottomAttach = ((uint)(2));
		w43.LeftAttach = ((uint)(1));
		w43.RightAttach = ((uint)(2));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._fitness2 = new global::Gtk.Label ();
		this._fitness2.Name = "_fitness2";
		this._fitness2.Xalign = 0F;
		this._fitness2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._fitness2);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table2 [this._fitness2]));
		w44.TopAttach = ((uint)(2));
		w44.BottomAttach = ((uint)(3));
		w44.LeftAttach = ((uint)(1));
		w44.RightAttach = ((uint)(2));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._inject1 = new global::Gtk.Button ();
		this._inject1.Sensitive = false;
		this._inject1.CanFocus = true;
		this._inject1.Name = "_inject1";
		this._inject1.UseUnderline = true;
		this._inject1.Label = global::Mono.Unix.Catalog.GetString ("Inject");
		this.table2.Add (this._inject1);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table2 [this._inject1]));
		w45.TopAttach = ((uint)(1));
		w45.BottomAttach = ((uint)(2));
		w45.LeftAttach = ((uint)(13));
		w45.RightAttach = ((uint)(14));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._inject2 = new global::Gtk.Button ();
		this._inject2.Sensitive = false;
		this._inject2.CanFocus = true;
		this._inject2.Name = "_inject2";
		this._inject2.UseUnderline = true;
		this._inject2.Label = global::Mono.Unix.Catalog.GetString ("Inject");
		this.table2.Add (this._inject2);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table2 [this._inject2]));
		w46.TopAttach = ((uint)(2));
		w46.BottomAttach = ((uint)(3));
		w46.LeftAttach = ((uint)(13));
		w46.RightAttach = ((uint)(14));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._max1 = new global::Gtk.Label ();
		this._max1.Name = "_max1";
		this._max1.Xalign = 0F;
		this._max1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._max1);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table2 [this._max1]));
		w47.TopAttach = ((uint)(1));
		w47.BottomAttach = ((uint)(2));
		w47.LeftAttach = ((uint)(5));
		w47.RightAttach = ((uint)(6));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._max2 = new global::Gtk.Label ();
		this._max2.Name = "_max2";
		this._max2.Xalign = 0F;
		this._max2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._max2);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table2 [this._max2]));
		w48.TopAttach = ((uint)(2));
		w48.BottomAttach = ((uint)(3));
		w48.LeftAttach = ((uint)(5));
		w48.RightAttach = ((uint)(6));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._save1 = new global::Gtk.Button ();
		this._save1.Sensitive = false;
		this._save1.CanFocus = true;
		this._save1.Name = "_save1";
		this._save1.UseUnderline = true;
		this._save1.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.table2.Add (this._save1);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table2 [this._save1]));
		w49.TopAttach = ((uint)(1));
		w49.BottomAttach = ((uint)(2));
		w49.LeftAttach = ((uint)(12));
		w49.RightAttach = ((uint)(13));
		w49.XOptions = ((global::Gtk.AttachOptions)(4));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._save2 = new global::Gtk.Button ();
		this._save2.Sensitive = false;
		this._save2.CanFocus = true;
		this._save2.Name = "_save2";
		this._save2.UseUnderline = true;
		this._save2.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.table2.Add (this._save2);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table2 [this._save2]));
		w50.TopAttach = ((uint)(2));
		w50.BottomAttach = ((uint)(3));
		w50.LeftAttach = ((uint)(12));
		w50.RightAttach = ((uint)(13));
		w50.XOptions = ((global::Gtk.AttachOptions)(4));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._sEnz1 = new global::Gtk.Label ();
		this._sEnz1.Name = "_sEnz1";
		this._sEnz1.Xalign = 0F;
		this._sEnz1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._sEnz1);
		global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table2 [this._sEnz1]));
		w51.TopAttach = ((uint)(1));
		w51.BottomAttach = ((uint)(2));
		w51.LeftAttach = ((uint)(11));
		w51.RightAttach = ((uint)(12));
		w51.XOptions = ((global::Gtk.AttachOptions)(4));
		w51.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._sEnz2 = new global::Gtk.Label ();
		this._sEnz2.Name = "_sEnz2";
		this._sEnz2.Xalign = 0F;
		this._sEnz2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._sEnz2);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table2 [this._sEnz2]));
		w52.TopAttach = ((uint)(2));
		w52.BottomAttach = ((uint)(3));
		w52.LeftAttach = ((uint)(11));
		w52.RightAttach = ((uint)(12));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._state1 = new global::Gtk.Label ();
		this._state1.Name = "_state1";
		this._state1.Xalign = 0F;
		this._state1.LabelProp = global::Mono.Unix.Catalog.GetString ("?");
		this.table2.Add (this._state1);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table2 [this._state1]));
		w53.TopAttach = ((uint)(1));
		w53.BottomAttach = ((uint)(2));
		w53.LeftAttach = ((uint)(2));
		w53.RightAttach = ((uint)(3));
		w53.XOptions = ((global::Gtk.AttachOptions)(4));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._state2 = new global::Gtk.Label ();
		this._state2.Name = "_state2";
		this._state2.Xalign = 0F;
		this._state2.LabelProp = global::Mono.Unix.Catalog.GetString ("?");
		this.table2.Add (this._state2);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table2 [this._state2]));
		w54.TopAttach = ((uint)(2));
		w54.BottomAttach = ((uint)(3));
		w54.LeftAttach = ((uint)(2));
		w54.RightAttach = ((uint)(3));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label = new global::Gtk.Label ();
		this.label.Name = "label";
		this.label.Xalign = 0F;
		this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("Enzyme #");
		this.table2.Add (this.label);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table2 [this.label]));
		w55.LeftAttach = ((uint)(9));
		w55.RightAttach = ((uint)(10));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.Xalign = 0F;
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Fitness");
		this.table2.Add (this.label12);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
		w56.LeftAttach = ((uint)(1));
		w56.RightAttach = ((uint)(2));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.Xalign = 0F;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Energy");
		this.table2.Add (this.label13);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table2 [this.label13]));
		w57.LeftAttach = ((uint)(4));
		w57.RightAttach = ((uint)(5));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.Xalign = 0F;
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Max");
		this.table2.Add (this.label14);
		global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table2 [this.label14]));
		w58.LeftAttach = ((uint)(5));
		w58.RightAttach = ((uint)(6));
		w58.XOptions = ((global::Gtk.AttachOptions)(4));
		w58.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.Xalign = 0F;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("D Cost");
		this.table2.Add (this.label15);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table2 [this.label15]));
		w59.LeftAttach = ((uint)(6));
		w59.RightAttach = ((uint)(7));
		w59.XOptions = ((global::Gtk.AttachOptions)(4));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.Xalign = 0F;
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("E Cost");
		this.table2.Add (this.label16);
		global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.table2 [this.label16]));
		w60.LeftAttach = ((uint)(7));
		w60.RightAttach = ((uint)(8));
		w60.XOptions = ((global::Gtk.AttachOptions)(4));
		w60.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.Xalign = 0F;
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Ex %");
		this.table2.Add (this.label17);
		global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table2 [this.label17]));
		w61.LeftAttach = ((uint)(8));
		w61.RightAttach = ((uint)(9));
		w61.XOptions = ((global::Gtk.AttachOptions)(4));
		w61.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.Xalign = 0F;
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Method");
		this.table2.Add (this.label18);
		global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table2 [this.label18]));
		w62.LeftAttach = ((uint)(3));
		w62.RightAttach = ((uint)(4));
		w62.XOptions = ((global::Gtk.AttachOptions)(4));
		w62.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label ();
		this.label25.Name = "label25";
		this.label25.Xalign = 0F;
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Enz # 1");
		this.table2.Add (this.label25);
		global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table2 [this.label25]));
		w63.LeftAttach = ((uint)(10));
		w63.RightAttach = ((uint)(11));
		w63.XOptions = ((global::Gtk.AttachOptions)(4));
		w63.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label26 = new global::Gtk.Label ();
		this.label26.Name = "label26";
		this.label26.Xalign = 0F;
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Enz # 2");
		this.table2.Add (this.label26);
		global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table2 [this.label26]));
		w64.LeftAttach = ((uint)(11));
		w64.RightAttach = ((uint)(12));
		w64.XOptions = ((global::Gtk.AttachOptions)(4));
		w64.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label28 = new global::Gtk.Label ();
		this.label28.Name = "label28";
		this.label28.Xalign = 0F;
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("State");
		this.table2.Add (this.label28);
		global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table2 [this.label28]));
		w65.LeftAttach = ((uint)(2));
		w65.RightAttach = ((uint)(3));
		w65.XOptions = ((global::Gtk.AttachOptions)(4));
		w65.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Fittest 1");
		this.table2.Add (this.label4);
		global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
		w66.TopAttach = ((uint)(1));
		w66.BottomAttach = ((uint)(2));
		w66.XOptions = ((global::Gtk.AttachOptions)(4));
		w66.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Fittest2");
		this.table2.Add (this.label5);
		global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
		w67.TopAttach = ((uint)(2));
		w67.BottomAttach = ((uint)(3));
		w67.XOptions = ((global::Gtk.AttachOptions)(4));
		w67.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook2.Add (this.table2);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Selection");
		this.notebook2.SetTabLabel (this.table2, this.label2);
		this.label2.ShowAll ();
		this.vbox3.Add (this.notebook2);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.notebook2]));
		w69.Position = 1;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w70.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this._action = new global::Gtk.Button ();
		this._action.Sensitive = false;
		this._action.CanFocus = true;
		this._action.Name = "_action";
		this._action.UseUnderline = true;
		this._action.Label = global::Mono.Unix.Catalog.GetString ("Go");
		this.hbox2.Add (this._action);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this._action]));
		w71.Position = 0;
		w71.Expand = false;
		w71.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		this.hbox2.Add (this.alignment3);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment3]));
		w72.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Close");
		this.hbox2.Add (this.button5);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button5]));
		w73.Position = 2;
		w73.Expand = false;
		w73.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w74.Position = 1;
		w74.Expand = false;
		w74.Fill = false;
		this.vbox2.Add (this.vbox1);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox1]));
		w75.Position = 2;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1464;
		this.DefaultHeight = 499;
		this._resetWarning.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this._reset.Clicked += new global::System.EventHandler (this.OnResetClicked);
		this._action.Clicked += new global::System.EventHandler (this.Action_Clicked);
	}
}
