
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Expander expander2;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.ComboBox _environments;
	
	private global::Gtk.SpinButton _generationsToRun;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.SpinButton spinbutton3;
	
	private global::Gtk.SpinButton spinbutton4;
	
	private global::Gtk.SpinButton spinbutton5;
	
	private global::Gtk.Label GtkLabel;
	
	private global::Gtk.HSeparator hseparator3;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label _generationLabel;
	
	private global::Gtk.Notebook notebook2;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Label _dCost1;
	
	private global::Gtk.Label _dCost2;
	
	private global::Gtk.Label _eCost1;
	
	private global::Gtk.Label _eCost2;
	
	private global::Gtk.Label _energy1;
	
	private global::Gtk.Label _energy2;
	
	private global::Gtk.Label _enzC1;
	
	private global::Gtk.Label _enzC2;
	
	private global::Gtk.Label _ex1;
	
	private global::Gtk.Label _ex2;
	
	private global::Gtk.Label _fEnz1;
	
	private global::Gtk.Label _fEnz2;
	
	private global::Gtk.Label _fitness1;
	
	private global::Gtk.Label _fitness2;
	
	private global::Gtk.Label _max1;
	
	private global::Gtk.Label _max2;
	
	private global::Gtk.Label label;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.Label label14;
	
	private global::Gtk.Label label15;
	
	private global::Gtk.Label label16;
	
	private global::Gtk.Label label17;
	
	private global::Gtk.Label label25;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Button _action;
	
	private global::Gtk.Alignment alignment3;
	
	private global::Gtk.Button button5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Harness");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		this.vbox2.BorderWidth = ((uint)(3));
		// Container child vbox2.Gtk.Box+BoxChild
		this.expander2 = new global::Gtk.Expander (null);
		this.expander2.CanFocus = true;
		this.expander2.Name = "expander2";
		this.expander2.Expanded = true;
		// Container child expander2.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(6)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this._environments = global::Gtk.ComboBox.NewText ();
		this._environments.Name = "_environments";
		this.table1.Add (this._environments);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this._environments]));
		w2.LeftAttach = ((uint)(5));
		w2.RightAttach = ((uint)(6));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this._generationsToRun = new global::Gtk.SpinButton (0, 100, 1);
		this._generationsToRun.CanFocus = true;
		this._generationsToRun.Name = "_generationsToRun";
		this._generationsToRun.Adjustment.PageIncrement = 10;
		this._generationsToRun.ClimbRate = 1;
		this._generationsToRun.Numeric = true;
		this._generationsToRun.Value = 10;
		this.table1.Add (this._generationsToRun);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this._generationsToRun]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Environment");
		this.table1.Add (this.label10);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
		w4.LeftAttach = ((uint)(4));
		w4.RightAttach = ((uint)(5));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.Ypad = 3;
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Lifetime Iterations");
		this.label11.Justify = ((global::Gtk.Justification)(3));
		this.table1.Add (this.label11);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label11]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Ypad = 3;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Pause After");
		this.label6.Justify = ((global::Gtk.Justification)(3));
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Ypad = 3;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Population Size");
		this.table1.Add (this.label7);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.Ypad = 3;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Genome Size");
		this.table1.Add (this.label8);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Iterations");
		this.table1.Add (this.label9);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbutton3 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton3.CanFocus = true;
		this.spinbutton3.Name = "spinbutton3";
		this.spinbutton3.Adjustment.PageIncrement = 10;
		this.spinbutton3.ClimbRate = 1;
		this.spinbutton3.Numeric = true;
		this.table1.Add (this.spinbutton3);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbutton3]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(3));
		w10.RightAttach = ((uint)(4));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbutton4 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton4.CanFocus = true;
		this.spinbutton4.Name = "spinbutton4";
		this.spinbutton4.Adjustment.PageIncrement = 10;
		this.spinbutton4.ClimbRate = 1;
		this.spinbutton4.Numeric = true;
		this.table1.Add (this.spinbutton4);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbutton4]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbutton5 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton5.CanFocus = true;
		this.spinbutton5.Name = "spinbutton5";
		this.spinbutton5.Adjustment.PageIncrement = 10;
		this.spinbutton5.ClimbRate = 1;
		this.spinbutton5.Numeric = true;
		this.table1.Add (this.spinbutton5);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbutton5]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add (this.table1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table1]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.expander2.Add (this.vbox4);
		this.GtkLabel = new global::Gtk.Label ();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		this.GtkLabel.UseUnderline = true;
		this.expander2.LabelWidget = this.GtkLabel;
		this.vbox2.Add (this.expander2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.expander2]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox2.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Generation");
		this.hbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this._generationLabel = new global::Gtk.Label ();
		this._generationLabel.Name = "_generationLabel";
		this._generationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.hbox1.Add (this._generationLabel);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._generationLabel]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(9)), true);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		this.table2.BorderWidth = ((uint)(2));
		// Container child table2.Gtk.Table+TableChild
		this._dCost1 = new global::Gtk.Label ();
		this._dCost1.Name = "_dCost1";
		this._dCost1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._dCost1);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this._dCost1]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.LeftAttach = ((uint)(4));
		w20.RightAttach = ((uint)(5));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._dCost2 = new global::Gtk.Label ();
		this._dCost2.Name = "_dCost2";
		this._dCost2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._dCost2);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this._dCost2]));
		w21.TopAttach = ((uint)(2));
		w21.BottomAttach = ((uint)(3));
		w21.LeftAttach = ((uint)(4));
		w21.RightAttach = ((uint)(5));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._eCost1 = new global::Gtk.Label ();
		this._eCost1.Name = "_eCost1";
		this._eCost1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._eCost1);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this._eCost1]));
		w22.TopAttach = ((uint)(1));
		w22.BottomAttach = ((uint)(2));
		w22.LeftAttach = ((uint)(5));
		w22.RightAttach = ((uint)(6));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._eCost2 = new global::Gtk.Label ();
		this._eCost2.Name = "_eCost2";
		this._eCost2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._eCost2);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this._eCost2]));
		w23.TopAttach = ((uint)(2));
		w23.BottomAttach = ((uint)(3));
		w23.LeftAttach = ((uint)(5));
		w23.RightAttach = ((uint)(6));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._energy1 = new global::Gtk.Label ();
		this._energy1.Name = "_energy1";
		this._energy1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._energy1);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this._energy1]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.LeftAttach = ((uint)(2));
		w24.RightAttach = ((uint)(3));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._energy2 = new global::Gtk.Label ();
		this._energy2.Name = "_energy2";
		this._energy2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._energy2);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this._energy2]));
		w25.TopAttach = ((uint)(2));
		w25.BottomAttach = ((uint)(3));
		w25.LeftAttach = ((uint)(2));
		w25.RightAttach = ((uint)(3));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._enzC1 = new global::Gtk.Label ();
		this._enzC1.Name = "_enzC1";
		this._enzC1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._enzC1);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this._enzC1]));
		w26.TopAttach = ((uint)(1));
		w26.BottomAttach = ((uint)(2));
		w26.LeftAttach = ((uint)(7));
		w26.RightAttach = ((uint)(8));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._enzC2 = new global::Gtk.Label ();
		this._enzC2.Name = "_enzC2";
		this._enzC2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._enzC2);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this._enzC2]));
		w27.TopAttach = ((uint)(2));
		w27.BottomAttach = ((uint)(3));
		w27.LeftAttach = ((uint)(7));
		w27.RightAttach = ((uint)(8));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._ex1 = new global::Gtk.Label ();
		this._ex1.Name = "_ex1";
		this._ex1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._ex1);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this._ex1]));
		w28.TopAttach = ((uint)(1));
		w28.BottomAttach = ((uint)(2));
		w28.LeftAttach = ((uint)(6));
		w28.RightAttach = ((uint)(7));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._ex2 = new global::Gtk.Label ();
		this._ex2.Name = "_ex2";
		this._ex2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._ex2);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2 [this._ex2]));
		w29.TopAttach = ((uint)(2));
		w29.BottomAttach = ((uint)(3));
		w29.LeftAttach = ((uint)(6));
		w29.RightAttach = ((uint)(7));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._fEnz1 = new global::Gtk.Label ();
		this._fEnz1.Name = "_fEnz1";
		this._fEnz1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._fEnz1);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2 [this._fEnz1]));
		w30.TopAttach = ((uint)(1));
		w30.BottomAttach = ((uint)(2));
		w30.LeftAttach = ((uint)(8));
		w30.RightAttach = ((uint)(9));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._fEnz2 = new global::Gtk.Label ();
		this._fEnz2.Name = "_fEnz2";
		this._fEnz2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._fEnz2);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2 [this._fEnz2]));
		w31.TopAttach = ((uint)(2));
		w31.BottomAttach = ((uint)(3));
		w31.LeftAttach = ((uint)(8));
		w31.RightAttach = ((uint)(9));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._fitness1 = new global::Gtk.Label ();
		this._fitness1.Name = "_fitness1";
		this._fitness1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._fitness1);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table2 [this._fitness1]));
		w32.TopAttach = ((uint)(1));
		w32.BottomAttach = ((uint)(2));
		w32.LeftAttach = ((uint)(1));
		w32.RightAttach = ((uint)(2));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._fitness2 = new global::Gtk.Label ();
		this._fitness2.Name = "_fitness2";
		this._fitness2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._fitness2);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2 [this._fitness2]));
		w33.TopAttach = ((uint)(2));
		w33.BottomAttach = ((uint)(3));
		w33.LeftAttach = ((uint)(1));
		w33.RightAttach = ((uint)(2));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._max1 = new global::Gtk.Label ();
		this._max1.Name = "_max1";
		this._max1.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._max1);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2 [this._max1]));
		w34.TopAttach = ((uint)(1));
		w34.BottomAttach = ((uint)(2));
		w34.LeftAttach = ((uint)(3));
		w34.RightAttach = ((uint)(4));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this._max2 = new global::Gtk.Label ();
		this._max2.Name = "_max2";
		this._max2.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table2.Add (this._max2);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table2 [this._max2]));
		w35.TopAttach = ((uint)(2));
		w35.BottomAttach = ((uint)(3));
		w35.LeftAttach = ((uint)(3));
		w35.RightAttach = ((uint)(4));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label = new global::Gtk.Label ();
		this.label.Name = "label";
		this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("Enzyme #");
		this.table2.Add (this.label);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2 [this.label]));
		w36.LeftAttach = ((uint)(7));
		w36.RightAttach = ((uint)(8));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Fitness");
		this.table2.Add (this.label12);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
		w37.LeftAttach = ((uint)(1));
		w37.RightAttach = ((uint)(2));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Energy");
		this.table2.Add (this.label13);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table2 [this.label13]));
		w38.LeftAttach = ((uint)(2));
		w38.RightAttach = ((uint)(3));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Max");
		this.table2.Add (this.label14);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table2 [this.label14]));
		w39.LeftAttach = ((uint)(3));
		w39.RightAttach = ((uint)(4));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("D Cost");
		this.table2.Add (this.label15);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table2 [this.label15]));
		w40.LeftAttach = ((uint)(4));
		w40.RightAttach = ((uint)(5));
		w40.XOptions = ((global::Gtk.AttachOptions)(4));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("E Cost");
		this.table2.Add (this.label16);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table2 [this.label16]));
		w41.LeftAttach = ((uint)(5));
		w41.RightAttach = ((uint)(6));
		w41.XOptions = ((global::Gtk.AttachOptions)(4));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Ex %");
		this.table2.Add (this.label17);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table2 [this.label17]));
		w42.LeftAttach = ((uint)(6));
		w42.RightAttach = ((uint)(7));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label ();
		this.label25.Name = "label25";
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Enz # 1");
		this.table2.Add (this.label25);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table2 [this.label25]));
		w43.LeftAttach = ((uint)(8));
		w43.RightAttach = ((uint)(9));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Fittest 1");
		this.table2.Add (this.label4);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
		w44.TopAttach = ((uint)(1));
		w44.BottomAttach = ((uint)(2));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Fittest2");
		this.table2.Add (this.label5);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
		w45.TopAttach = ((uint)(2));
		w45.BottomAttach = ((uint)(3));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		this.notebook2.Add (this.table2);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Selection");
		this.notebook2.SetTabLabel (this.table2, this.label2);
		this.label2.ShowAll ();
		this.vbox3.Add (this.notebook2);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.notebook2]));
		w47.Position = 1;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w48.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this._action = new global::Gtk.Button ();
		this._action.Sensitive = false;
		this._action.CanFocus = true;
		this._action.Name = "_action";
		this._action.UseUnderline = true;
		this._action.Label = global::Mono.Unix.Catalog.GetString ("Go");
		this.hbox2.Add (this._action);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this._action]));
		w49.Position = 0;
		w49.Expand = false;
		w49.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		this.hbox2.Add (this.alignment3);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment3]));
		w50.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Close");
		this.hbox2.Add (this.button5);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button5]));
		w51.Position = 2;
		w51.Expand = false;
		w51.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		this.vbox2.Add (this.vbox1);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox1]));
		w53.Position = 2;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 648;
		this.DefaultHeight = 499;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this._action.Clicked += new global::System.EventHandler (this.Action_Clicked);
	}
}
