
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Expander expander2;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.ComboBox _environments;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.SpinButton spinbutton2;
	
	private global::Gtk.SpinButton spinbutton3;
	
	private global::Gtk.SpinButton spinbutton4;
	
	private global::Gtk.Label GtkLabel;
	
	private global::Gtk.HSeparator hseparator3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Harness");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		this.vbox2.BorderWidth = ((uint)(3));
		// Container child vbox2.Gtk.Box+BoxChild
		this.expander2 = new global::Gtk.Expander (null);
		this.expander2.CanFocus = true;
		this.expander2.Name = "expander2";
		this.expander2.Expanded = true;
		// Container child expander2.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox4.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(6)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this._environments = global::Gtk.ComboBox.NewText ();
		this._environments.Name = "_environments";
		this.table1.Add (this._environments);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this._environments]));
		w2.LeftAttach = ((uint)(5));
		w2.RightAttach = ((uint)(6));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Environment");
		this.table1.Add (this.label10);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
		w3.LeftAttach = ((uint)(4));
		w3.RightAttach = ((uint)(5));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Ypad = 3;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Pause After");
		this.label6.Justify = ((global::Gtk.Justification)(3));
		this.table1.Add (this.label6);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Ypad = 3;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Population Size");
		this.table1.Add (this.label7);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.Ypad = 3;
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Genome Size");
		this.table1.Add (this.label8);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Iterations");
		this.table1.Add (this.label9);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbutton2 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton2.CanFocus = true;
		this.spinbutton2.Name = "spinbutton2";
		this.spinbutton2.Adjustment.PageIncrement = 10;
		this.spinbutton2.ClimbRate = 1;
		this.spinbutton2.Numeric = true;
		this.table1.Add (this.spinbutton2);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbutton2]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbutton3 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton3.CanFocus = true;
		this.spinbutton3.Name = "spinbutton3";
		this.spinbutton3.Adjustment.PageIncrement = 10;
		this.spinbutton3.ClimbRate = 1;
		this.spinbutton3.Numeric = true;
		this.table1.Add (this.spinbutton3);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbutton3]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(3));
		w9.RightAttach = ((uint)(4));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbutton4 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton4.CanFocus = true;
		this.spinbutton4.Name = "spinbutton4";
		this.spinbutton4.Adjustment.PageIncrement = 10;
		this.spinbutton4.ClimbRate = 1;
		this.spinbutton4.Numeric = true;
		this.table1.Add (this.spinbutton4);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinbutton4]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add (this.table1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.expander2.Add (this.vbox4);
		this.GtkLabel = new global::Gtk.Label ();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		this.GtkLabel.UseUnderline = true;
		this.expander2.LabelWidget = this.GtkLabel;
		this.vbox2.Add (this.expander2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.expander2]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox2.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 674;
		this.DefaultHeight = 466;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
